# UEC Issue Template
# Standardizes submission of errata, ECNs, editorial or technical changes,
# and questions against the UEC Specification.

name: UEC Specification Submission
description: Propose an errata, ECN, or other revision to the UEC Specification
title: "[TYPE]: Summary of the change"
labels:
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your submission
        Replace `[TYPE]` in the title to match your selection

  - type: dropdown
    id: classification
    attributes:
      label: Classification Tag
      description: Select the change type
      options:
        - "— Select classification —"
        - Errata
        - ECN
        - Editorial
        - Technical
        - Question
      default: 0
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Impact Level
      description: Select an impact level
      options:
        - High (functionality or security issues)
        - Medium (partial feature impact)
        - Low (minor issues or cosmetic)
      default: 1
    validations:
      required: true

  - type: textarea
    id: spec-sections
    attributes:
      label: Affected Section(s)
      description: List section numbers and titles, one per line
    validations:
      required: true

  - type: textarea
    id: original-text
    attributes:
      label: Original Text
      description: Paste the exact text you want to change
    validations:
      required: true

  - type: textarea
    id: proposed-resolution
    attributes:
      label: Proposed Resolution
      description: Enter the replacement text per the UEC Specification
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Justification & Additional Context
      description: Explain why this change is necessary
    validations:
      required: false

  - type: checkboxes
    id: triage-checklist
    attributes:
      label: Triage Checklist (for maintainers)
      description: Steps for maintainers to verify
      options:
        - Classification and impact reviewed
        - Section reference verified
        - Assigned to appropriate team
        - Version tag applied
