# Auto-Labeler for UEC Specification Issues
# Automatically adds a `type/<classification>` label to newly opened issue

name: Auto-Label UEC Issues

"on":
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add-classification-label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply classification label
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body;
            const match = body.match(/Classification Tag\s*\n-?\s*(\w+)/i);
            if (match) {
              const label = `type/${match[1].trim()}`;
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [label]
              });
            }
