# .github/workflows/build-jenkins-image.yml
name: Build Jenkins Image

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Jenkins Docker image
        run: |
          docker build -t ghcr.io/lfit/jenkins:main ./build

      - name: Test Jenkins image
        run: |
          docker run -d --name jenkins-test -p 8080:8080 ghcr.io/lfit/jenkins:main

          echo "Waiting for Jenkins to start..."
          timeout=60
          interval=5
          elapsed=0

          until curl -s http://localhost:8080/login > /dev/null; do
            sleep $interval
            elapsed=$((elapsed + interval))
            echo "Waiting... ${elapsed}s"
            if [ $elapsed -ge $timeout ]; then
              echo "Jenkins did not become available on port 8080 in time"
              docker logs jenkins-test
              docker rm -f jenkins-test
              exit 1
            fi
          done

          echo "Jenkins is up on port 8080"
          docker logs jenkins-test | tee jenkins.log
          docker logs jenkins-test | grep -E "Jenkins is fully up and running|Completed initialization"

          docker rm -f jenkins-test

      - name: Push Jenkins image to GHCR
        if: github.repository == 'lfit/jenkins-gitops'
        run: |
          docker push ghcr.io/lfit/jenkins:main
