name: Update Staging Image

on:
  workflow_run:
    workflows: ["Build and Test Jenkins Image"]
    types:
      - completed
    branches:
      - main

jobs:
  update-staging-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get latest image tag
        id: get-tag
        run: |
          LATEST_TAG="main-$(echo ${{ github.sha }} | cut -c1-7)"
          echo "image-tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "Found new image tag: ${LATEST_TAG}"

      - name: Update staging values.yaml
        id: update-values
        run: |
          echo "Updating staging/values.yaml with new image tag..."

          sed -i 's|repository: "jenkins/jenkins"|repository: "ghcr.io/vvalderrv/jenkins"|g' staging/values.yaml
          sed -i 's|tag: "lts-jdk17"|tag: "${{ steps.get-tag.outputs.image-tag }}"|g' staging/values.yaml

          if git diff --quiet staging/values.yaml; then
            echo "No changes needed in staging/values.yaml"
            echo "changes-made=false" >> $GITHUB_OUTPUT
          else
            echo "Changes made to staging/values.yaml:"
            git diff staging/values.yaml
            echo "changes-made=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request for staging update
        if: steps.update-values.outputs.changes-made == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            Update staging Jenkins image to ${{ steps.get-tag.outputs.image-tag }}

            - Updates staging/values.yaml with new image tag
            - Triggered by successful image build: ${{ github.sha }}
            - Image: ghcr.io/vvalderrv/jenkins:${{ steps.get-tag.outputs.image-tag }}
          title: "Update staging Jenkins image to ${{ steps.get-tag.outputs.image-tag }}"
          body: |
            ## Staging Image Update

            This PR automatically updates the Jenkins staging environment with a newly built and tested image.

            **Changes:**
            - New Image Tag: ${{ steps.get-tag.outputs.image-tag }}
            - Repository: ghcr.io/vvalderrv/jenkins
            - Build Status: All tests passed
            - Triggered by: ${{ github.event.workflow_run.html_url }}

            **What happens after merge:**
            1. ArgoCD will detect the changes in staging/values.yaml
            2. Jenkins staging environment will automatically update
            3. New image will be deployed with all tested plugins and tools

            This PR was automatically created by the Update Staging Image workflow.
          branch: update-staging-image-${{ steps.get-tag.outputs.image-tag }}
          delete-branch: true

      - name: Output update status
        run: |
          if [ "${{ steps.update-values.outputs.changes-made }}" == "true" ]; then
            echo "Staging image update PR created successfully"
          else
            echo "No staging update needed - image already current"
          fi
